### ISSUE TITLE
Parse SDK and Its value

### ISSUE THREAD

**Issue by wonderfan** [wonderfan/javascript#3]
There is the parse official site:
- [ parse sdk](https://www.parse.com/)

**Comment by wonderfan** [comment]
Here is the doc: [docs](https://www.parse.com/docs)

**Comment by gimm** [comment]
I have barely no knowledge on mobile development, but I know mobile is hot and tons of new stuff coming out everyday.
IMHO, every solution that tries to resolve all problems is just like jack of all trades, given that mobile development is such a broad topic.
There's a `lib over framework` trend with web development in 2014, I think this also applies here.
Hope you can come up with more insight with all these frameworks/lib.

**Comment by wonderfan** [comment]
It leverages the Backbone and NodeJs to provide one-stop solution
